# Generated by Django 4.0 on 2021-12-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_date',
            new_name='date_published',
        ),
    ]
